# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.network_detail import NetworkDetail  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, networks: List[NetworkDetail]=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param networks: The networks of this InlineResponse2004.  # noqa: E501
        :type networks: List[NetworkDetail]
        """
        self.swagger_types = {
            'networks': List[NetworkDetail]
        }

        self.attribute_map = {
            'networks': 'networks'
        }
        self._networks = networks

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def networks(self) -> List[NetworkDetail]:
        """Gets the networks of this InlineResponse2004.


        :return: The networks of this InlineResponse2004.
        :rtype: List[NetworkDetail]
        """
        return self._networks

    @networks.setter
    def networks(self, networks: List[NetworkDetail]):
        """Sets the networks of this InlineResponse2004.


        :param networks: The networks of this InlineResponse2004.
        :type networks: List[NetworkDetail]
        """

        self._networks = networks
