# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class JobIdMonitorizeBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: str=None, probe_id: int=None):  # noqa: E501
        """JobIdMonitorizeBody - a model defined in Swagger

        :param file: The file of this JobIdMonitorizeBody.  # noqa: E501
        :type file: str
        :param probe_id: The probe_id of this JobIdMonitorizeBody.  # noqa: E501
        :type probe_id: int
        """
        self.swagger_types = {
            'file': str,
            'probe_id': int
        }

        self.attribute_map = {
            'file': 'file',
            'probe_id': 'probeId'
        }
        self._file = file
        self._probe_id = probe_id

    @classmethod
    def from_dict(cls, dikt) -> 'JobIdMonitorizeBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The jobId_monitorize_body of this JobIdMonitorizeBody.  # noqa: E501
        :rtype: JobIdMonitorizeBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this JobIdMonitorizeBody.

        Archivo resultante del trabajo de scan.  # noqa: E501

        :return: The file of this JobIdMonitorizeBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this JobIdMonitorizeBody.

        Archivo resultante del trabajo de scan.  # noqa: E501

        :param file: The file of this JobIdMonitorizeBody.
        :type file: str
        """

        self._file = file

    @property
    def probe_id(self) -> int:
        """Gets the probe_id of this JobIdMonitorizeBody.

        Id de la sonda que sube el archivo.  # noqa: E501

        :return: The probe_id of this JobIdMonitorizeBody.
        :rtype: int
        """
        return self._probe_id

    @probe_id.setter
    def probe_id(self, probe_id: int):
        """Sets the probe_id of this JobIdMonitorizeBody.

        Id de la sonda que sube el archivo.  # noqa: E501

        :param probe_id: The probe_id of this JobIdMonitorizeBody.
        :type probe_id: int
        """

        self._probe_id = probe_id
